### ISSUE TITLE
TypeError: Cannot read property 'start' of null in pure_component.js

### ISSUE THREAD

**Issue by ritz078** [reactjs/react-codemod#64] opened 2016-07-08 20:15 UTC
Here's the error: 

```
TypeError: Cannot read property 'start' of null
    at reportSkipped (pure-component.js:86:28)
    at pure-component.js:97:9
    at Array.filter (native)
    at Collection.filter (/Users/ritz078/.npm-packages/lib/node_modules/jscodeshift/dist/Collection.js:60:46)
    at module.exports (pure-component.js:94:6)
```

**Comment by keyanzhang** [comment] 2016-07-08 20:16
Thanks for reporting this. Could you provide a sample of the code that caused this error?

**Comment by ritz078** [comment] 2016-07-09 16:33
```js
import React  from 'react';

export default class SingleAccordion extends React.Component {
  static propTypes = {
    actions  : React.PropTypes.object
  };

  constructor (props, context) {
    super(props, context);
    this.state = {
      expanded: false,
    };
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick () {
    this.setState( { expanded : !this.state.expanded });
    if (this.props.trackClick && !this.state.expanded) {
      this.props.trackClick();
    }
  }

  render () {
    const Child = this.props.childElement ;
    const style = {} ;
    style.height = this.state.expanded ? 'auto' : this.props.height;
    const button = this.state.expanded ? this.props.expanded : this.props.collapsed ;

    return (
      <div>
        <div className='accordion-container f14black' style={style}>
          <Child content={this.props.content}/>
        </div>
        <div className="accordion-button" onClick={this.handleClick}>{button}</div>
      </div>
    );
  }
}
```

**Comment by DrewML** [comment] 2016-08-14 06:48
Huh. So this was/is failing because the `node` being returned for this `ClassDeclaration` is missing the `loc` object (it's `null`). Reproducible [here](http://astexplorer.net/#/PifJKAJ3we/1).

Could be fixed in this codemod itself by not reporting line/column information whenever it's missing (luckily this is only happening when the codemod tries to report that a `Class` was skipped), but this is probably an issue with the `babel-core` v5 parser that `jscodeshift` is using by default.

I tried stepping around the issue by specifying `--parser babylon` to `jscodeshift`, but `ast-types` then fails under the hood because `Babylon` diverges from the `ESTree` spec and uses the `StringLiteral` node type instead of the `Literal` type.

@keyanzhang Interested in a PR just to prevent throwing an exception, or you want to leave as-is?

**Comment by keyanzhang** [comment] 2016-08-22 14:15
Thanks @DrewML! Sorry I've been traveling and just got back to the states. Could you try to switch to the Flow parser to see if it fixes the issue?

**Comment by ritz078** [comment] 2016-09-12 11:32
any update on this ?

**Comment by surgeboris** [comment] 2016-09-23 17:43
I've encountered same problem. Neither `--parser babylon` nor `--parser flow` does solve issue.
So I've created PR https://github.com/reactjs/react-codemod/pull/78

**Closed** 2016-11-06 15:52 UTC
