### ISSUE TITLE
Unknown property React.createRef

### ISSUE THREAD

**Issue by vitaliyhayda** [reactjs/react-codemod#245] opened 2019-10-05 15:26 UTC
Error: Unknown property React.createRef

**Comment by threepointone** [comment] 2019-10-05 17:08
Happy to investigate more of you can provide a reproducing usecase, thank you!

**Comment by threepointone** [comment] 2019-10-07 10:51
Closing because there are no details provided, happy to discuss and reopen if you can provide more information.

**Closed by threepointone** 2019-10-07 10:51 UTC
