### ISSUE TITLE
Codemod React.proptypes results in " TypeError: Cannot read property 'number' of undefined " 

### ISSUE THREAD

**Issue by bellancaf** [reactjs/react-codemod#226] opened 2019-07-04 17:21 UTC
I am migrating from 15.4- to 16.8 and I used the prop-types script. 
Once I deploy I end up with this problem -> TypeError: Cannot read property 'number' of undefined. 

I  have 12 files with Proptypes.number and all of them import correctly prop-types. 

I pass them as follows => 

```jsx
StepComponent.propTypes = {
  defaultStepContainerWidth: PropTypes.number.isRequired,
  stepsLength: PropTypes.number.isRequired,
  renderSteps: PropTypes.func.isRequired
};

export default StepComponent;
```
What am I missing? :/

**Comment by threepointone** [comment] 2019-07-22 09:15
Can you make a git repo with the reproduction? Can't tell without looking closer

**Comment by threepointone** [comment] 2019-10-05 11:40
I'm going to close this because there isn't a reproducing example. I'm happy to reopen if one is provided.

**Closed by threepointone** 2019-10-05 11:40 UTC
Labels: needs information
