### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by bsqtmp** [reactjs/react-codemod#153] opened 2017-06-26 09:21 UTC
yarn install failed with this error:
`	Configuration for rule "react/jsx-sort-props" is invalid:
	Value "data["0"].shorthandLast" has additional properties.
        Configuration for rule "react/jsx-sort-props" is invalid:
	Value "data["0"].shorthandLast" has additional properties.
`

**Comment by bvaughn** [comment] 2017-07-28 04:04
Looks like `jsx-sort-props` has something to do with yannickcr/eslint-plugin-react (a dev dependency of this project) but I'm not sure why you'd be seeing this error on install. The issue doesn't seem specific to react-codemod though. See:
* https://github.com/airbnb/javascript/issues/1016
* https://github.com/airbnb/javascript/issues/979
* https://github.com/react-boilerplate/react-boilerplate/issues/895
* etc

A fresh install (of this project) works fine for me. Maybe check out the troubleshooting suggestions mentioned on the issues I linked to and see if any of them help you out?

I'm going to close this issue for now since I don't think this is caused by react-codemod.

**Closed by bvaughn** 2017-07-28 04:04 UTC
